#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Feb 11 04:08:55 2010

import wx
import webbrowser
import wx.lib.iewin_old as iewin
import wx.lib.sized_controls as sc
import time
import httplib
import os

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # run web server
        #config.run_server()

        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FULL_REPAINT_ON_RESIZE|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_main_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(3001, "Home", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "Save as", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "Exit", "", wx.ITEM_NORMAL)
        self.frame_main_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(3002, "Search", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(3003, "Ranking", "", wx.ITEM_NORMAL)
        self.frame_main_menubar.Append(wxglade_tmp_menu, "View")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(3004, "Config", "", wx.ITEM_NORMAL)
        self.frame_main_menubar.Append(wxglade_tmp_menu, "Config")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(3007, "Update from ...", "", wx.ITEM_NORMAL)
        self.frame_main_menubar.Append(wxglade_tmp_menu, "DB")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(3006, "Help", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(3005, "Update", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_ABOUT, "About", "", wx.ITEM_NORMAL)
        self.frame_main_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_main_menubar)
        # Menu Bar end
        self.frame_main_statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.frame_main_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_DOCKABLE|wx.TB_3DBUTTONS)
        self.SetToolBar(self.frame_main_toolbar)
        self.frame_main_toolbar.AddLabelTool(2001, "Home", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\homepage.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Home", "")
        self.frame_main_toolbar.AddLabelTool(2002, "Search", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\search.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Search", "")
        self.frame_main_toolbar.AddLabelTool(2003, "Ranking", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\ranking.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Ranking", "")
        self.frame_main_toolbar.AddSeparator()
        self.frame_main_toolbar.AddLabelTool(2004, "Config", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\config.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Config", "")
        self.frame_main_toolbar.AddLabelTool(2005, "Update", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\update.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Update", "")
        self.frame_main_toolbar.AddSeparator()
        self.frame_main_toolbar.AddLabelTool(wx.ID_ABOUT, "About", wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\about.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "About", "")
        # Tool Bar end

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.home_handler, id=3001)
        self.Bind(wx.EVT_MENU, self.saveas_handler, id=wx.ID_SAVEAS)
        self.Bind(wx.EVT_MENU, self.exit_handler, id=wx.ID_EXIT)
        self.Bind(wx.EVT_MENU, self.search_handler, id=3002)
        self.Bind(wx.EVT_MENU, self.ranking_handler, id=3003)
        self.Bind(wx.EVT_MENU, self.config_handler, id=3004)
        self.Bind(wx.EVT_MENU, self.db_update_handler, id=3007)
        self.Bind(wx.EVT_MENU, self.help_handler, id=3006)
        self.Bind(wx.EVT_MENU, self.update_handler, id=3005)
        self.Bind(wx.EVT_MENU, self.about_handler, id=wx.ID_ABOUT)
        self.Bind(wx.EVT_TOOL, self.home_handler, id=2001)
        self.Bind(wx.EVT_TOOL, self.search_handler, id=2002)
        self.Bind(wx.EVT_TOOL, self.ranking_handler, id=2003)
        self.Bind(wx.EVT_TOOL, self.config_handler, id=2004)
        self.Bind(wx.EVT_TOOL, self.update_handler, id=2005)
        self.Bind(wx.EVT_TOOL, self.about_handler, id=wx.ID_ABOUT)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("SimpleCD Desktop Preview")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Python26\\WS\\SimpleCD Desktop\\res\\logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((900, 599))
        self.SetFocus()
        self.frame_main_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_main_statusbar_fields = ["Welcome to SimpleCD Desktop"]
        for i in range(len(frame_main_statusbar_fields)):
            self.frame_main_statusbar.SetStatusText(frame_main_statusbar_fields[i], i)
        self.frame_main_toolbar.SetToolBitmapSize((32, 32))
        self.frame_main_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer_main)
        self.Layout()
        self.Centre()
        # end wxGlade

        # add homepage
        self.ie = iewin.IEHtmlWindow(self)
        sizer_main.Add(self.ie, 1, wx.GROW)
    self.ie.LoadUrl('http://localhost:%s/'%config.SS_PORT)

    def saveas_handler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `saveas_handler' not implemented!"
        event.Skip()

    def exit_handler(self, event): # wxGlade: MainFrame.<event_handler>
        self.Close()

    def config_handler(self, event): # wxGlade: MainFrame.<event_handler>
        dialog_config = ConfigDialog(None, -1, "Configurations")
        app.SetTopWindow(dialog_config)
        dialog_config.ShowModal()
        dialog_config.Destroy()

    def about_handler(self, event): # wxGlade: MainFrame.<event_handler>
        frame_about = AboutFrame(None, -1, "")
        app.SetTopWindow(frame_main)
        frame_about.Show()

    def home_handler(self, event): # wxGlade: MainFrame.<event_handler>
        self.ie.LoadUrl('http://localhost:%s/'%config.SS_PORT)

    def ranking_handler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `ranking_handler' not implemented!"
        event.Skip()

    def search_handler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `search_handler' not implemented"
        event.Skip()

    def update_handler(self, event): # wxGlade: MainFrame.<event_handler>
        ids = update.get_update_ids()
        if len(ids) == 0:
            dialog_updated = UpdatedDialog(None, -1, "")
            app.SetTopWindow(dialog_updated)
            dialog_updated.ShowModal()
            dialog_updated.Destroy()
            return
        elif ids[0].startswith('new:'):
            dlg = wx.MessageDialog(self, ids[0][4:],
                               'Update Error',
                               wx.OK | wx.ICON_INFORMATION
                               #wx.YES_NO | wx.NO_DEFAULT | wx.CANCEL | wx.ICON_INFORMATION
                               )
            dlg.ShowModal()
            dlg.Destroy()
        elif config.SS_UPDATE_SOURCE == 'verycd':
            max = len(ids)
            print max
            dlg = wx.ProgressDialog("Updating Databases...",
                               'Processing 1/%d' % (max*2/3),
                               maximum = max,
                               parent=self,
                               style = wx.PD_CAN_ABORT
                                | wx.PD_APP_MODAL
                                | wx.PD_ELAPSED_TIME
                                | wx.PD_ESTIMATED_TIME
                                #| wx.PD_REMAINING_TIME
                                )
            import fetchvc
            lastid = fetchvc.update_ids(ids,dlg.Update,max)
            print lastid
            dlg.Update(max,'Finished')
            update.update_db_updtime(lastid)
            dlg.Destroy()
        elif config.SS_UPDATE_SOURCE == 'simplecd':
            group = 5
            max = ((len(ids)-1)/group+1)*3*2
            dlg = wx.ProgressDialog("Updating Databases...",
                               "Downloading 1/%d"%(max/2),
                               maximum = max,
                               parent=self,
                               style = wx.PD_CAN_ABORT
                                | wx.PD_APP_MODAL
                                | wx.PD_ELAPSED_TIME
                                | wx.PD_ESTIMATED_TIME
                                #| wx.PD_REMAINING_TIME
                                )
            keepGoing = True
            count = 0
            httpconn = httplib.HTTPConnection("www.simplecd.org")
            # group ids, 100 per group
            for i in range(0,max/3/2):
                subids = ids[i*group:i*group+group]
                for dbname in ['verycd','lock']:
                    update.download_updates(dbname,subids,httpconn=httpconn)
                    count += 1
                    (keepGoing, skip) = dlg.Update(count, "Downloading %d/%d"%(count,max/2))
                    if not keepGoing:
                        break
                if not keepGoing:
                    break
            # Apply_updates
         
        
    def help_handler(self, event): # wxGlade: MainFrame.<event_handler>
        webbrowser.open_new_tab('http://www.simplecd.org/bbs/')

    def db_update_handler(self, event): # wxGlade: MainFrame.<event_handler>
        dlg = wx.FileDialog(
            self, message="Choose a file",
            defaultDir=os.getcwd(), 
            defaultFile="",
            wildcard="targz files (*.tar.gz)|*.tar.gz",
            style=wx.OPEN | wx.MULTIPLE | wx.CHANGE_DIR
            )
        paths = None
        if dlg.ShowModal() == wx.ID_OK:
            paths = dlg.GetPaths()
        dlg.Destroy()
        updts = paths
        if updts:
            max = len(updts)*3*100000
            dlg = wx.ProgressDialog("Updating from files...",
                               "Extracting...Please be patient ",
                               maximum = max,
                               parent=self,
                               style = wx.PD_CAN_ABORT
                                | wx.PD_APP_MODAL
                                | wx.PD_ELAPSED_TIME
                                | wx.PD_ESTIMATED_TIME
                                #| wx.PD_REMAINING_TIME
                                )
            count = 1
            for updt in updts:
                import tarfile
                tar = tarfile.open(updt)
                tar.extractall(path=config.SS_HOME_DIR)
                tar.close()               
                update.apply_updates('verycd',dlg.Update,max-1) 
                update.apply_updates('comment',dlg.Update,max-1)
                update.apply_updates('lock',dlg.Update,max-1)
            dlg.Update(max,'Finished')
            update.delete_tempfiles()
            update.update_timestamp()
        dlg.Destroy()


# end of class MainFrame

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_main = MainFrame(None, -1, "")
    app.SetTopWindow(frame_main)
    frame_main.Show()
    app.MainLoop()
